# Site settings
title:  Arthur Su Blog
description:    Have fun
baseurl:
url:    https://guyverone.github.io

# Build settings
markdown: kramdown
kramdown:
    auto_ids: true
    input:    GFM
    syntax_highlighter: rouge

highlighter:    rouge
